from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping

from .ast_nodes import SourceSpan


class Severity(Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    FATAL = "fatal"


@dataclass(frozen=True)
class Diagnostic:
    """A structured diagnostic message."""

    code: str
    message: str
    severity: Severity
    source: SourceSpan | None = None
    rule_id: str | None = None
    suggestion: str | None = None
    target: str | None = None
    data: Mapping[str, Any] | None = None


class DiagnosticCodes:
    MISSING_PROFILE = "MISSING_PROFILE"
    TXT_UNKNOWN_MARKER = "TXT_UNKNOWN_MARKER"
    TXT_CYRILLIC_IN_MARKER = "TXT_CYRILLIC_IN_MARKER"
    TXT_DUPLICATE_ID = "TXT_DUPLICATE_ID"
    TXT_MISSING_BLOCK_END = "TXT_MISSING_BLOCK_END"
    TXT_MISSING_METADATA = "TXT_MISSING_METADATA"
    TXT_MALFORMED_ATTRIBUTE = "TXT_MALFORMED_ATTRIBUTE"
    TXT_INVALID_TABLE_SHAPE = "TXT_INVALID_TABLE_SHAPE"
    TXT_IMAGE_NOT_FOUND = "TXT_IMAGE_NOT_FOUND"
    TXT_IMAGE_OUTSIDE_ROOT = "TXT_IMAGE_OUTSIDE_ROOT"
    TXT_UNSUPPORTED_SYNTAX = "TXT_UNSUPPORTED_SYNTAX"
    INVALID_HEADING_LEVEL = "INVALID_HEADING_LEVEL"
    HEADING_LEVEL_SKIPPED = "HEADING_LEVEL_SKIPPED"
    FORMAT_MARGIN_LEFT = "FORMAT_MARGIN_LEFT"
    FORMAT_MARGIN_RIGHT = "FORMAT_MARGIN_RIGHT"
    FORMAT_MARGIN_TOP = "FORMAT_MARGIN_TOP"
    FORMAT_MARGIN_BOTTOM = "FORMAT_MARGIN_BOTTOM"
    FORMAT_FONT_NAME = "FORMAT_FONT_NAME"
    FORMAT_FONT_SIZE = "FORMAT_FONT_SIZE"
    FORMAT_FONT_COLOR = "FORMAT_FONT_COLOR"
    FORMAT_LINE_SPACING = "FORMAT_LINE_SPACING"
    FORMAT_INDENT = "FORMAT_INDENT"
    FORMAT_ALIGNMENT = "FORMAT_ALIGNMENT"
    FORMAT_PARAGRAPH_SPACING = "FORMAT_PARAGRAPH_SPACING"
    FORMAT_HEADING_BOLD = "FORMAT_HEADING_BOLD"
    FORMAT_HEADING_NO_PERIOD = "FORMAT_HEADING_NO_PERIOD"
    HEADING_HYPHENATION = "HEADING_HYPHENATION"
    HEADING_TWO_SENTENCE = "HEADING_TWO_SENTENCE"
    HEADING_POINT_REQUIRES_SUBPOINTS = "HEADING_POINT_REQUIRES_SUBPOINTS"
    HEADING_SPACING_BEFORE = "HEADING_SPACING_BEFORE"
    HEADING_SPACING_AFTER = "HEADING_SPACING_AFTER"
    FORMAT_TABLE_FONT_SIZE = "FORMAT_TABLE_FONT_SIZE"
    FORMAT_TABLE_FORBIDDEN_SERIAL_COLUMN = "FORMAT_TABLE_FORBIDDEN_SERIAL_COLUMN"
    FORMAT_TABLE_HEADER_PERIOD = "FORMAT_TABLE_HEADER_PERIOD"
    FORMAT_TABLE_DIAGONAL_SPLIT = "FORMAT_TABLE_DIAGONAL_SPLIT"
    FORMAT_TABLE_CELL_PADDING = "FORMAT_TABLE_CELL_PADDING"
    FORMAT_TABLE_ITALIC_LETTER = "FORMAT_TABLE_ITALIC_LETTER"
    FORMAT_TABLE_BORDERS = "FORMAT_TABLE_BORDERS"
    FORMAT_ABBREVIATIONS_TABLE = "FORMAT_ABBREVIATIONS_TABLE"
    FORMAT_RULE_NOT_SUPPORTED = "FORMAT_RULE_NOT_SUPPORTED"
    FORMAT_ROLE_UNRECOGNIZED = "FORMAT_ROLE_UNRECOGNIZED"
    FORMAT_PAGE_NUMBERING = "FORMAT_PAGE_NUMBERING"
    TOC_NOT_REQUIRED_FOR_SHORT_DOCUMENT = "TOC_NOT_REQUIRED_FOR_SHORT_DOCUMENT"
    TOC_INDENT_LEVEL = "TOC_INDENT_LEVEL"
    TOC_ENTRY_MISMATCH = "TOC_ENTRY_MISMATCH"
    TOC_APPENDIX_GROUPING = "TOC_APPENDIX_GROUPING"
    FIGURE_MISSING_IMAGE = "FIGURE_MISSING_IMAGE"
    FIGURE_NEVER_REFERENCED = "FIGURE_NEVER_REFERENCED"
    FIGURE_PLACEMENT_NEXT_PAGE = "FIGURE_PLACEMENT_NEXT_PAGE"
    FIGURE_MULTI_SHEET_LABEL = "FIGURE_MULTI_SHEET_LABEL"
    FORMULA_EXPLANATION_MARKER = "FORMULA_EXPLANATION_MARKER"
    FORMULA_REPEATED_SYMBOL = "FORMULA_REPEATED_SYMBOL"
    FORMULA_CONSECUTIVE_COMMA = "FORMULA_CONSECUTIVE_COMMA"
    FORMULA_LINE_CONTINUATION = "FORMULA_LINE_CONTINUATION"
    BIBLIOGRAPHY_MISSING_FIELD = "BIBLIOGRAPHY_MISSING_FIELD"
    BIBLIOGRAPHY_GROUPING_METHOD = "BIBLIOGRAPHY_GROUPING_METHOD"
    BIBLIOGRAPHY_RUSSIAN_FIRST = "BIBLIOGRAPHY_RUSSIAN_FIRST"
    BIBLIOGRAPHY_SEPARATOR = "BIBLIOGRAPHY_SEPARATOR"
    CITATION_MALFORMED = "CITATION_MALFORMED"
    CITATION_PAGE_RANGE_REVERSED = "CITATION_PAGE_RANGE_REVERSED"
    CITATION_NUMBER_DUPLICATED = "CITATION_NUMBER_DUPLICATED"
    FOOTNOTE_DUPLICATE = "FOOTNOTE_DUPLICATE"
    FOOTNOTE_UNMATCHED_ANCHOR = "FOOTNOTE_UNMATCHED_ANCHOR"
    FOOTNOTE_UNMATCHED_BODY = "FOOTNOTE_UNMATCHED_BODY"
    FOOTNOTE_FORMAT = "FOOTNOTE_FORMAT"
    REFERENCE_UNRESOLVED = "REFERENCE_UNRESOLVED"
    REFERENCE_AMBIGUOUS = "REFERENCE_AMBIGUOUS"
    REFERENCE_OBJECT_UNUSED = "REFERENCE_OBJECT_UNUSED"
    REFERENCE_BIBLIOGRAPHY_UNUSED = "REFERENCE_BIBLIOGRAPHY_UNUSED"
    REFERENCE_APPENDIX_UNUSED = "REFERENCE_APPENDIX_UNUSED"
    APPENDIX_AUTOLETTER_ASSIGNED = "APPENDIX_AUTOLETTER_ASSIGNED"
    APPENDIX_LETTER_SEQUENCE = "APPENDIX_LETTER_SEQUENCE"
    APPENDIX_CONTINUATION_LABEL = "APPENDIX_CONTINUATION_LABEL"
    APPENDIX_SECTION_NUMBERING = "APPENDIX_SECTION_NUMBERING"
    STRUCTURE_TITLE_PAGE_MISSING = "STRUCTURE_TITLE_PAGE_MISSING"
    STRUCTURE_MAIN_PART_MISSING = "STRUCTURE_MAIN_PART_MISSING"
    STRUCTURE_REQUIRED_SECTION_MISSING = "STRUCTURE_REQUIRED_SECTION_MISSING"
    STRUCTURE_DUPLICATE_SECTION = "STRUCTURE_DUPLICATE_SECTION"
    STRUCTURE_SECTION_OUT_OF_ORDER = "STRUCTURE_SECTION_OUT_OF_ORDER"
    STRUCTURE_APPENDIX_BEFORE_SOURCES = "STRUCTURE_APPENDIX_BEFORE_SOURCES"
    STRUCTURE_SOURCES_BEFORE_ABBREVIATIONS = "STRUCTURE_SOURCES_BEFORE_ABBREVIATIONS"
    PROJECT_DESIGNATION_FORMAT = "PROJECT_DESIGNATION_FORMAT"
    PROJECT_DESIGNATION_CODE = "PROJECT_DESIGNATION_CODE"
    PROJECT_DESIGNATION_YEAR = "PROJECT_DESIGNATION_YEAR"
    PROJECT_DESIGNATION_SCHEMA = "PROJECT_DESIGNATION_SCHEMA"
    PROJECT_DESIGNATION_MISSING = "PROJECT_DESIGNATION_MISSING"
    STYLE_ABBREVIATION_NOT_INTRODUCED = "STYLE_ABBREVIATION_NOT_INTRODUCED"
    STYLE_ABBREVIATION_IN_HEADING = "STYLE_ABBREVIATION_IN_HEADING"
    STYLE_UNIT_INCONSISTENT = "STYLE_UNIT_INCONSISTENT"
    GRAPHIC_DRAWING_SCALE = "GRAPHIC_DRAWING_SCALE"
    GRAPHIC_DRAWING_FONT = "GRAPHIC_DRAWING_FONT"
    GRAPHIC_SHEET_FRAME = "GRAPHIC_SHEET_FRAME"
    POSTER_FILL_DENSITY = "POSTER_FILL_DENSITY"
    POSTER_TITLE_BLOCK_REVERSE = "POSTER_TITLE_BLOCK_REVERSE"
    SLIDE_REQUIRED_FIRST_FIELDS = "SLIDE_REQUIRED_FIRST_FIELDS"
    SLIDE_FILL_DENSITY = "SLIDE_FILL_DENSITY"
    SLIDE_HEADER_CONTINUITY = "SLIDE_HEADER_CONTINUITY"
    SLIDE_A4_PRINT_OUT = "SLIDE_A4_PRINT_OUT"
