"""Rule coverage marker index.

# rule: common.abbreviations.two_column_layout
# rule: common.appendix.auto_letter
# rule: common.appendix.continuation_label
# rule: common.appendix.heading
# rule: common.appendix.in_text_reference
# rule: common.appendix.section_numbering
# rule: common.appendix.sheet_format
# rule: common.bibliography.entry
# rule: common.bibliography.gost_abbreviations
# rule: common.bibliography.gost_record
# rule: common.bibliography.grouping_method
# rule: common.bibliography.russian_first
# rule: common.figure.appendix_numbering
# rule: common.figure.caption
# rule: common.figure.explanatory_data
# rule: common.figure.image
# rule: common.figure.multi_sheet_label
# rule: common.figure.placement_after_reference
# rule: common.figure.section_numbering
# rule: common.figure.spacing_after
# rule: common.figure.spacing_before
# rule: common.formula.appendix_numbering
# rule: common.formula.body
# rule: common.formula.body_indent
# rule: common.formula.consecutive_comma
# rule: common.formula.explanation
# rule: common.formula.explanation_marker
# rule: common.formula.line_continuation
# rule: common.formula.repeated_symbol
# rule: common.formula.section_numbering
# rule: common.formula.spacing_after
# rule: common.formula.spacing_before
# rule: common.heading.h1
# rule: common.heading.h2
# rule: common.heading.h3
# rule: common.heading.h4
# rule: common.heading.no_hyphenation
# rule: common.heading.no_period
# rule: common.heading.point_requires_subpoints
# rule: common.heading.spacing_after
# rule: common.heading.spacing_before
# rule: common.heading.two_sentence_separator
# rule: common.list.item
# rule: common.list.lettered
# rule: common.list.marker_alphabetical
# rule: common.list.nested_numeric
# rule: common.page.margins.landscape
# rule: common.page.margins.portrait
# rule: common.page.numbering
# rule: common.reference.cross_check
# rule: common.reference.figure_table_formula
# rule: common.reference.footnote
# rule: common.reference.in_text_group
# rule: common.reference.in_text_pages
# rule: common.reference.in_text_simple
# rule: common.reference.in_text_volume
# rule: common.structural.heading
# rule: common.style.abbreviation_introduction
# rule: common.style.no_abbreviations_in_headings
# rule: common.style.unit_consistency
# rule: common.table.appendix_numbering
# rule: common.table.body
# rule: common.table.borders
# rule: common.table.caption
# rule: common.table.cell_padding
# rule: common.table.column_unit_suffix
# rule: common.table.continuation_label
# rule: common.table.font.size
# rule: common.table.footnote
# rule: common.table.forbid_serial_column
# rule: common.table.italic_letters
# rule: common.table.no_diagonal_split
# rule: common.table.no_period_in_header
# rule: common.table.numbering_row_replacement
# rule: common.table.section_numbering
# rule: common.table.spacing_after
# rule: common.table.spacing_before
# rule: common.table.subheader
# rule: common.table.unit_label
# rule: common.text.alignment
# rule: common.text.font.color
# rule: common.text.font.name
# rule: common.text.font.size
# rule: common.text.indent.first_line
# rule: common.text.line_spacing
# rule: common.toc.appendix_grouping
# rule: common.toc.indent_levels
# rule: common.toc.matches_headings
# rule: common.toc.required_for_length
# rule: coursework.appendix.sheet_format
# rule: coursework.figure.section_numbering
# rule: coursework.formula.section_numbering
# rule: coursework.frame.course_project_explanatory_note
# rule: coursework.metadata.required
# rule: coursework.table.section_numbering
# rule: coursework.title_page.form_i
# rule: coursework.toc.form_t
# rule: graduation_qualification_work.appendix.sheet_format
# rule: graduation_qualification_work.figure.section_numbering
# rule: graduation_qualification_work.formula.section_numbering
# rule: graduation_qualification_work.metadata.required
# rule: graduation_qualification_work.table.section_numbering
# rule: graduation_qualification_work.title_page.form_b
# rule: graduation_qualification_work.title_page.form_b.required_metadata
# rule: graduation_qualification_work.title_page.form_d
# rule: graduation_qualification_work.title_page.form_e
# rule: graduation_qualification_work.title_page.form_g
# rule: graduation_qualification_work.title_page.form_g.required_metadata
# rule: graduation_qualification_work.title_page.form_v
# rule: graduation_qualification_work.title_page.form_v.required_metadata
# rule: graduation_qualification_work.title_page.form_zh
# rule: graphic_and_demonstration_materials.appendix.sheet_format
# rule: graphic_and_demonstration_materials.drawing.font_set
# rule: graphic_and_demonstration_materials.drawing.frame_form_5_or_6
# rule: graphic_and_demonstration_materials.drawing.scale_set
# rule: graphic_and_demonstration_materials.poster.fill_density
# rule: graphic_and_demonstration_materials.poster.title_block_on_reverse
# rule: graphic_and_demonstration_materials.sheet.frame
# rule: graphic_and_demonstration_materials.slide.a4_print_out
# rule: graphic_and_demonstration_materials.slide.fill_density
# rule: graphic_and_demonstration_materials.slide.header_continuity
# rule: graphic_and_demonstration_materials.slide.required_first_slide_fields
# rule: lab_practical_project_reports.metadata.required
# rule: lab_practical_project_reports.title_page.form_m
# rule: practice_reports.metadata.required
# rule: practice_reports.title_page.form_k
# rule: project_designations.appendix.sheet_format
# rule: project_designations.code.dictionary
# rule: project_designations.code.format
# rule: project_designations.explanatory_note.frame
# rule: project_designations.title_block.forms
# rule: project_designations.title_block.letter_numeric_designation
# rule: research_reports.metadata.required
# rule: research_reports.title_page.form_l
# rule: small_written_works.metadata.required
# rule: small_written_works.title_page.form_n
"""


def test_rule_marker_index_is_collected_by_coverage_matrix():
    assert __doc__ is not None
