"""Formatting rule definitions for SFU standard STU 7.5-07-2021.

Each rule is keyed by ``{doc}.{section}.{element}`` and traceable to a section
in ``docs/formatting requirements/``. Parameters are stored as plain Python
types (mm, pt, dimensionless numbers, RGB triplets) so the registry stays free
of rendering-library imports. The loader translates parameters into renderer
units when building the legacy ``SIBFUConfig`` compatibility layer.
"""

from __future__ import annotations

from sfu_converter.domain.formatting import (
    FormattingRule,
    RuleSeverity,
    RuleStatus,
)

_COMMON_DOC = "docs/formatting requirements/common.md"
_COURSEWORK_DOC = "docs/formatting requirements/coursework.md"
_GRADUATION_DOC = "docs/formatting requirements/graduation_qualification_work.md"
_LAB_DOC = "docs/formatting requirements/lab_practical_project_reports.md"
_PRACTICE_DOC = "docs/formatting requirements/practice_reports.md"
_RESEARCH_DOC = "docs/formatting requirements/research_reports.md"
_SMALL_WRITTEN_DOC = "docs/formatting requirements/small_written_works.md"
_GRAPHIC_DOC = "docs/formatting requirements/graphic_and_demonstration_materials.md"
_PROJECT_DESIGNATION_DOC = "docs/formatting requirements/project_designations.md"


COMMON_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="common.page.margins.portrait",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"top_mm": 20, "bottom_mm": 20, "left_mm": 30, "right_mm": 10},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="A4 portrait margins: top 20mm, bottom 20mm, left 30mm, right 10mm",
    ),
    FormattingRule(
        id="common.text.font.name",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"font_name": "Times New Roman"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text font: Times New Roman",
    ),
    FormattingRule(
        id="common.text.font.size",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"font_size_pt": 14},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text font size: 14pt",
    ),
    FormattingRule(
        id="common.text.font.color",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"color_rgb": (0, 0, 0)},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text color: black",
    ),
    FormattingRule(
        id="common.text.alignment",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"alignment": "justify"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text alignment: justified",
    ),
    FormattingRule(
        id="common.text.indent.first_line",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"indent_cm": 1.25},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="First line indent: 12.5mm (1.25cm)",
    ),
    FormattingRule(
        id="common.text.line_spacing",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"spacing": 1.5},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Line spacing: 1.5",
    ),
    FormattingRule(
        id="common.page.numbering",
        source_doc=_COMMON_DOC,
        source_section="Page numbering",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "position": "bottom_center",
            "font_name": "Times New Roman",
            "font_size_pt": 14,
            "format": "arabic",
            "skip_first_page": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Arabic page numbers centered at bottom, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.structural.heading",
        source_doc=_COMMON_DOC,
        source_section="Core Text Document Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "headings": (
                "РЕФЕРАТ",
                "АННОТАЦИЯ",
                "СОДЕРЖАНИЕ",
                "ВВЕДЕНИЕ",
                "ЗАКЛЮЧЕНИЕ",
                "СПИСОК СОКРАЩЕНИЙ",
                "СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ",
                "ПРИЛОЖЕНИЕ",
            ),
            "alignment": "center",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "uppercase": True,
            "page_break_before": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Structural section headings: new page, centered, bold, uppercase",
    ),
    FormattingRule(
        id="common.heading.h1",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H1 heading: centered, bold, single line spacing",
    ),
    FormattingRule(
        id="common.heading.h2",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H2 heading: left-aligned, bold, single line spacing",
    ),
    FormattingRule(
        id="common.heading.h3",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H3 heading: left-aligned, single line spacing",
    ),
    FormattingRule(
        id="common.heading.no_period",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Headings must not end with a period",
    ),
    FormattingRule(
        id="common.heading.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line before a heading (line spacing 0.5)",
    ),
    FormattingRule(
        id="common.heading.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line after a heading separating it from the body text",
    ),
    FormattingRule(
        id="common.list.item",
        source_doc=_COMMON_DOC,
        source_section="Division of Text - Enumeration rules",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "justify",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Enumeration item: paragraph indent, justified, 1.5 line spacing",
    ),
    FormattingRule(
        id="common.figure.caption",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Figure caption: centered, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.figure.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.8, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above an illustration",
    ),
    FormattingRule(
        id="common.figure.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below an illustration",
    ),
    FormattingRule(
        id="common.formula.body",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "number_tab_pos_cm": 16.5,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description=("Formula paragraph: centered, with auto-number right-aligned in parentheses"),
    ),
    FormattingRule(
        id="common.formula.explanation",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Formula symbol explanation: left-aligned, no first-line indent",
    ),
    FormattingRule(
        id="common.formula.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1.0, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above a formula",
    ),
    FormattingRule(
        id="common.formula.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1.0, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below a formula",
    ),
    FormattingRule(
        id="common.bibliography.entry",
        source_doc=_COMMON_DOC,
        source_section="List of Used Sources",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "justify",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Bibliography entry: justified, paragraph indent, 1.5 line spacing",
    ),
    FormattingRule(
        id="common.figure.image",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "line_spacing": 1.5,
            "max_width_cm": 15,
            "dpi": (96, 96),
            "format": "PNG",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Image placement: centered, max width 15cm",
    ),
    FormattingRule(
        id="common.table.caption",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table caption: left-aligned, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.table.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above a table",
    ),
    FormattingRule(
        id="common.table.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below a table",
    ),
    FormattingRule(
        id="common.table.cell_padding",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"padding_pt": 6},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Table cell vertical padding: 6pt before/after",
    ),
    FormattingRule(
        id="common.table.font.size",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"min_size_pt": 10, "max_size_pt": 12},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table text font size must be 10-12pt",
    ),
    FormattingRule(
        id="common.table.body",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={
            "font_size_pt": 12,
            "header_font_size_pt": 12,
            "header_bold": True,
            "line_spacing": 1.0,
            "header_repeat_on_pages": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description=("Table body: 12pt font, single spacing, bold header repeated on continuation pages"),
    ),
)


LAB_PRACTICAL_PROJECT_REPORT_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="lab_practical_project_reports.metadata.required",
        source_doc=_LAB_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("document_type", "title", "student", "group", "teacher"),
            "optional_metadata": ("record_book", "institute", "department", "city", "year"),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Lab/practical/project report metadata required by the title page form",
    ),
    FormattingRule(
        id="lab_practical_project_reports.title_page.form_m",
        source_doc=_LAB_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_m",
            "default_document_type": "ОТЧЕТ ПО ЛАБОРАТОРНОЙ РАБОТЕ",
            "required_metadata": ("title", "student", "group", "teacher"),
            "optional_metadata": ("document_type", "record_book", "institute", "department", "city", "year"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix M title page for lab, practical, and project-completion reports",
    ),
    FormattingRule(
        id="lab_practical_project_reports.structure.required_sections",
        source_doc=_LAB_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


PRACTICE_REPORT_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="practice_reports.metadata.required",
        source_doc=_PRACTICE_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "practice_place",
                "university_supervisor",
                "enterprise_supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Practice report metadata required by the title page form",
    ),
    FormattingRule(
        id="practice_reports.title_page.form_k",
        source_doc=_PRACTICE_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_k",
            "default_document_type": "ОТЧЕТ О ПРАКТИКЕ",
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "practice_place",
                "university_supervisor",
                "enterprise_supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix K title page for practice reports",
    ),
    FormattingRule(
        id="practice_reports.structure.required_sections",
        source_doc=_PRACTICE_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


RESEARCH_REPORT_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="research_reports.metadata.required",
        source_doc=_RESEARCH_DOC,
        source_section="Title Page for Master's Research-Work Report",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "master_program",
                "program_head",
                "approval_date",
                "supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Research report metadata required by the title page form",
    ),
    FormattingRule(
        id="research_reports.title_page.form_l",
        source_doc=_RESEARCH_DOC,
        source_section="Title Page for Master's Research-Work Report",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_l",
            "default_document_type": "ОТЧЕТ О НАУЧНО-ИССЛЕДОВАТЕЛЬСКОЙ РАБОТЕ",
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "master_program",
                "program_head",
                "approval_date",
                "supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix L title page for master's research-work reports",
    ),
    FormattingRule(
        id="research_reports.structure.required_sections",
        source_doc=_RESEARCH_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


SMALL_WRITTEN_WORK_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="small_written_works.metadata.required",
        source_doc=_SMALL_WRITTEN_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "discipline",
                "teacher",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Small written work metadata required by the title page form",
    ),
    FormattingRule(
        id="small_written_works.title_page.form_n",
        source_doc=_SMALL_WRITTEN_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_n",
            "default_document_type": "РЕФЕРАТ",
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "discipline",
                "teacher",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix N title page for referats, calculation works, control works, and essays",
    ),
    FormattingRule(
        id="small_written_works.structure.required_sections",
        source_doc=_SMALL_WRITTEN_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


COURSEWORK_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="coursework.metadata.required",
        source_doc=_COURSEWORK_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group", "supervisor"),
            "optional_metadata": (
                "document_type",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Coursework metadata required by the title page form",
    ),
    FormattingRule(
        id="coursework.title_page.form_i",
        source_doc=_COURSEWORK_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_i",
            "default_document_type": "КУРСОВАЯ РАБОТА",
            "required_metadata": ("title", "student", "group", "supervisor"),
            "optional_metadata": (
                "document_type",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix I title page for course projects and course works",
    ),
    FormattingRule(
        id="coursework.structure.required_sections",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Work Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory for course works",
    ),
    FormattingRule(
        id="coursework.frame.course_project_explanatory_note",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Project Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"requires_frame": True, "title_block_forms": ("form_1", "form_2", "form_3", "form_4")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Course project explanatory notes use framed sheets and title blocks",
    ),
)


GRADUATION_QUALIFICATION_WORK_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="graduation_qualification_work.metadata.required",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "supervisor"),
            "optional_metadata": (
                "vkr_type",
                "direction",
                "program",
                "reviewer",
                "department_head",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR metadata required by the selected title page form",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_b",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_b",
            "document_type": "МАГИСТЕРСКАЯ ДИССЕРТАЦИЯ",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix B title page for master dissertations",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_v",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_v",
            "document_type": "ДИПЛОМНЫЙ ПРОЕКТ",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix V title page for diploma projects",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_g",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_g",
            "document_type": "ДИПЛОМНАЯ РАБОТА",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix G title page for diploma works",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_d",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_d",
            "document_type": "БАКАЛАВРСКАЯ РАБОТА",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix D title page for bachelor works",
    ),
    FormattingRule(
        id="graduation_qualification_work.structure.assignment_after_title",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Assignment",
        severity=RuleSeverity.REQUIRED,
        parameters={"assignment_after_title_page": True, "counted_in_page_total": False},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR assignment is inserted after the title page and excluded from page count",
    ),
)


GRAPHIC_AND_DEMONSTRATION_MATERIAL_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="graphic_and_demonstration_materials.sheet.frame",
        source_doc=_GRAPHIC_DOC,
        source_section="Drawings and Schemes",
        severity=RuleSeverity.REQUIRED,
        parameters={"requires_frame": True, "title_block_forms": ("form_5", "form_6")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Drawings and schemes require a frame and title block",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.poster.fill_density",
        source_doc=_GRAPHIC_DOC,
        source_section="Posters",
        severity=RuleSeverity.REQUIRED,
        parameters={"min_fill_percent": 70, "format": "A1"},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Posters are A1 sheets filled to at least 70 percent",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.slide.required_first_slide_fields",
        source_doc=_GRAPHIC_DOC,
        source_section="Slides",
        severity=RuleSeverity.REQUIRED,
        parameters={"fields": ("university", "institute", "title", "student", "supervisor", "city", "year")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="First slide must include institution, topic, author, supervisor, city, and year",
    ),
)


PROJECT_DESIGNATION_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="project_designations.explanatory_note.frame",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Explanatory Note Sheets",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "left_sheet_edge_to_frame_mm": 20,
            "top_right_bottom_edge_to_frame_mm": 5,
            "text_to_frame_horizontal_mm": 5,
            "text_to_frame_vertical_mm": 15,
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Diploma and course project explanatory notes use framed A4 sheets",
    ),
    FormattingRule(
        id="project_designations.title_block.forms",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Main Title-Block Forms",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "text_first_sheet_forms": ("form_1", "form_2"),
            "text_following_sheet_forms": ("form_3", "form_4"),
            "graphic_sheet_forms": ("form_5", "form_6"),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title-block forms used for explanatory notes and graphic sheets",
    ),
    FormattingRule(
        id="project_designations.letter_numeric_designation",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Letter-Numeric Designation",
        severity=RuleSeverity.REQUIRED,
        parameters={"title_block_field": 2, "may_include_year": True},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Diploma/course project materials receive a letter-numeric designation in title-block field 2",
    ),
)


ALL_RULES: tuple[FormattingRule, ...] = (
    *COMMON_RULES,
    *LAB_PRACTICAL_PROJECT_REPORT_RULES,
    *PRACTICE_REPORT_RULES,
    *RESEARCH_REPORT_RULES,
    *SMALL_WRITTEN_WORK_RULES,
    *COURSEWORK_RULES,
    *GRADUATION_QUALIFICATION_WORK_RULES,
    *GRAPHIC_AND_DEMONSTRATION_MATERIAL_RULES,
    *PROJECT_DESIGNATION_RULES,
)

RULES_BY_ID: dict[str, FormattingRule] = {rule.id: rule for rule in ALL_RULES}
