"""Formatting rule definitions for SFU standard STU 7.5-07-2021.

Each rule is keyed by ``{doc}.{section}.{element}`` and traceable to a section
in ``docs/formatting requirements/``. Parameters are stored as plain Python
types (mm, pt, dimensionless numbers, RGB triplets) so the registry stays free
of rendering-library imports. The loader translates parameters into renderer
units when building the legacy ``SIBFUConfig`` compatibility layer.
"""

from __future__ import annotations

from sfu_converter.domain.formatting import (
    FormattingRule,
    RuleSeverity,
    RuleStatus,
)

_COMMON_DOC = "docs/formatting requirements/common.md"


COMMON_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="common.page.margins.portrait",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"top_mm": 20, "bottom_mm": 20, "left_mm": 30, "right_mm": 10},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="A4 portrait margins: top 20mm, bottom 20mm, left 30mm, right 10mm",
    ),
    FormattingRule(
        id="common.text.font.name",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"font_name": "Times New Roman"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text font: Times New Roman",
    ),
    FormattingRule(
        id="common.text.font.size",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"font_size_pt": 14},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text font size: 14pt",
    ),
    FormattingRule(
        id="common.text.font.color",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"color_rgb": (0, 0, 0)},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text color: black",
    ),
    FormattingRule(
        id="common.text.alignment",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"alignment": "justify"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text alignment: justified",
    ),
    FormattingRule(
        id="common.text.indent.first_line",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"indent_cm": 1.25},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="First line indent: 12.5mm (1.25cm)",
    ),
    FormattingRule(
        id="common.text.line_spacing",
        source_doc=_COMMON_DOC,
        source_section="Page and paper setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"spacing": 1.5},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Line spacing: 1.5",
    ),
    FormattingRule(
        id="common.page.numbering",
        source_doc=_COMMON_DOC,
        source_section="Page numbering",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "position": "bottom_center",
            "font_name": "Times New Roman",
            "font_size_pt": 14,
            "format": "arabic",
            "skip_first_page": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Arabic page numbers centered at bottom, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.structural.heading",
        source_doc=_COMMON_DOC,
        source_section="Core Text Document Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "headings": (
                "РЕФЕРАТ",
                "АННОТАЦИЯ",
                "СОДЕРЖАНИЕ",
                "ВВЕДЕНИЕ",
                "ЗАКЛЮЧЕНИЕ",
                "СПИСОК СОКРАЩЕНИЙ",
                "СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ",
                "ПРИЛОЖЕНИЕ",
            ),
            "alignment": "center",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "uppercase": True,
            "page_break_before": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Structural section headings: new page, centered, bold, uppercase",
    ),
    FormattingRule(
        id="common.heading.h1",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H1 heading: centered, bold, single line spacing",
    ),
    FormattingRule(
        id="common.heading.h2",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H2 heading: left-aligned, bold, single line spacing",
    ),
    FormattingRule(
        id="common.heading.h3",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H3 heading: left-aligned, single line spacing",
    ),
    FormattingRule(
        id="common.heading.no_period",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Headings must not end with a period",
    ),
    FormattingRule(
        id="common.heading.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line before a heading (line spacing 0.5)",
    ),
    FormattingRule(
        id="common.heading.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line after a heading separating it from the body text",
    ),
    FormattingRule(
        id="common.list.item",
        source_doc=_COMMON_DOC,
        source_section="Division of Text - Enumeration rules",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "justify",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Enumeration item: paragraph indent, justified, 1.5 line spacing",
    ),
    FormattingRule(
        id="common.figure.caption",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Figure caption: centered, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.figure.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.8, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above an illustration",
    ),
    FormattingRule(
        id="common.figure.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below an illustration",
    ),
    FormattingRule(
        id="common.formula.body",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "number_tab_pos_cm": 16.5,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description=(
            "Formula paragraph: centered, with auto-number right-aligned in parentheses"
        ),
    ),
    FormattingRule(
        id="common.formula.explanation",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Formula symbol explanation: left-aligned, no first-line indent",
    ),
    FormattingRule(
        id="common.formula.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1.0, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above a formula",
    ),
    FormattingRule(
        id="common.formula.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1.0, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below a formula",
    ),
    FormattingRule(
        id="common.bibliography.entry",
        source_doc=_COMMON_DOC,
        source_section="List of Used Sources",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "justify",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Bibliography entry: justified, paragraph indent, 1.5 line spacing",
    ),
    FormattingRule(
        id="common.figure.image",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "line_spacing": 1.5,
            "max_width_cm": 15,
            "dpi": (96, 96),
            "format": "PNG",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Image placement: centered, max width 15cm",
    ),
    FormattingRule(
        id="common.table.caption",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Table caption: left-aligned, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.table.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above a table",
    ),
    FormattingRule(
        id="common.table.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below a table",
    ),
    FormattingRule(
        id="common.table.cell_padding",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"padding_pt": 6},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Table cell vertical padding: 6pt before/after",
    ),
    FormattingRule(
        id="common.table.font.size",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"min_size_pt": 10, "max_size_pt": 12},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table text font size must be 10-12pt",
    ),
    FormattingRule(
        id="common.table.body",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={
            "font_size_pt": 12,
            "header_font_size_pt": 12,
            "header_bold": True,
            "line_spacing": 1.0,
            "header_repeat_on_pages": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description=(
            "Table body: 12pt font, single spacing, bold header repeated on continuation pages"
        ),
    ),
)


RULES_BY_ID: dict[str, FormattingRule] = {rule.id: rule for rule in COMMON_RULES}
