"""Formatting rule definitions for SFU standard STU 7.5-07-2021.

Each rule is keyed by ``{doc}.{section}.{element}`` and traceable to a section
in ``docs/formatting requirements/``. Parameters are stored as plain Python
types (mm, pt, dimensionless numbers, RGB triplets) so the registry stays free
of rendering-library imports. The loader translates parameters into renderer
units when building the legacy ``SIBFUConfig`` compatibility layer.
"""

from __future__ import annotations

from sfu_converter.domain.formatting import (
    FormattingRule,
    RuleSeverity,
    RuleStatus,
)

_COMMON_DOC = "docs/formatting requirements/common.md"
_COURSEWORK_DOC = "docs/formatting requirements/coursework.md"
_GRADUATION_DOC = "docs/formatting requirements/graduation_qualification_work.md"
_LAB_DOC = "docs/formatting requirements/lab_practical_project_reports.md"
_PRACTICE_DOC = "docs/formatting requirements/practice_reports.md"
_RESEARCH_DOC = "docs/formatting requirements/research_reports.md"
_SMALL_WRITTEN_DOC = "docs/formatting requirements/small_written_works.md"
_GRAPHIC_DOC = "docs/formatting requirements/graphic_and_demonstration_materials.md"
_PROJECT_DESIGNATION_DOC = "docs/formatting requirements/project_designations.md"


COMMON_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="common.page.margins.portrait",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"top_mm": 20, "bottom_mm": 20, "left_mm": 30, "right_mm": 10},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="A4 portrait margins: top 20mm, bottom 20mm, left 30mm, right 10mm",
    ),
    FormattingRule(
        id="common.text.font.name",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"font_name": "Times New Roman"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text font: Times New Roman",
    ),
    FormattingRule(
        id="common.text.font.size",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"font_size_pt": 14},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text font size: 14pt",
    ),
    FormattingRule(
        id="common.text.font.color",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"color_rgb": (0, 0, 0)},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text color: black",
    ),
    FormattingRule(
        id="common.text.alignment",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"alignment": "justify"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Body text alignment: justified",
    ),
    FormattingRule(
        id="common.text.indent.first_line",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"indent_cm": 1.25},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="First line indent: 12.5mm (1.25cm)",
    ),
    FormattingRule(
        id="common.text.line_spacing",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"spacing": 1.5},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Line spacing: 1.5",
    ),
    FormattingRule(
        id="common.page.numbering",
        source_doc=_COMMON_DOC,
        source_section="Page Numbering",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "position": "bottom_center",
            "font_name": "Times New Roman",
            "font_size_pt": 14,
            "format": "arabic",
            "skip_first_page": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Arabic page numbers centered at bottom, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.structural.heading",
        source_doc=_COMMON_DOC,
        source_section="Core Text Document Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "headings": (
                "РЕФЕРАТ",
                "АННОТАЦИЯ",
                "СОДЕРЖАНИЕ",
                "ВВЕДЕНИЕ",
                "ЗАКЛЮЧЕНИЕ",
                "СПИСОК СОКРАЩЕНИЙ",
                "СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ",
                "ПРИЛОЖЕНИЕ",
            ),
            "alignment": "center",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "uppercase": True,
            "page_break_before": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Structural section headings: new page, centered, bold, uppercase",
    ),
    FormattingRule(
        id="common.toc.required_for_length",
        source_doc=_COMMON_DOC,
        source_section="Contents",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"omit_when_pages_lte": 24, "always_allowed_profiles": ("graduation_qualification_work",)},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Contents are not recommended for documents of 24 pages or less",
    ),
    FormattingRule(
        id="common.toc.indent_levels",
        source_doc=_COMMON_DOC,
        source_section="Contents",
        severity=RuleSeverity.REQUIRED,
        parameters={"level_indent_cm": (0, 0.5, 1.0, 1.5)},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Contents indentation: sections flush left, each lower level indented by two characters",
    ),
    FormattingRule(
        id="common.toc.matches_headings",
        source_doc=_COMMON_DOC,
        source_section="Contents",
        severity=RuleSeverity.REQUIRED,
        parameters={"exact_heading_text": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Contents entries must match document headings",
    ),
    FormattingRule(
        id="common.toc.appendix_grouping",
        source_doc=_COMMON_DOC,
        source_section="Contents",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"min_group_size": 3, "format": "Приложения А–Т"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Three or more contiguous appendices may be grouped into one contents entry",
    ),
    FormattingRule(
        id="common.heading.h1",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H1 heading: centered, bold, single line spacing",
    ),
    FormattingRule(
        id="common.heading.h2",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H2 heading: left-aligned, bold, single line spacing",
    ),
    FormattingRule(
        id="common.heading.h3",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="H3 heading: left-aligned, single line spacing",
    ),
    FormattingRule(
        id="common.heading.no_period",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Headings must not end with a period",
    ),
    FormattingRule(
        id="common.heading.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Empty line before a heading (line spacing 0.5)",
    ),
    FormattingRule(
        id="common.heading.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Empty line after a heading separating it from the body text",
    ),
    FormattingRule(
        id="common.list.item",
        source_doc=_COMMON_DOC,
        source_section="Division of Text",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "justify",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Enumeration item: paragraph indent, justified, 1.5 line spacing",
    ),
    FormattingRule(
        id="common.figure.caption",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Figure caption: centered, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.figure.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.8, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above an illustration",
    ),
    FormattingRule(
        id="common.figure.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below an illustration",
    ),
    FormattingRule(
        id="common.formula.body",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "number_tab_pos_cm": 16.5,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description=("Formula paragraph: centered, with auto-number right-aligned in parentheses"),
    ),
    FormattingRule(
        id="common.formula.explanation",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Formula symbol explanation: left-aligned, no first-line indent",
    ),
    FormattingRule(
        id="common.formula.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1.0, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line above a formula",
    ),
    FormattingRule(
        id="common.formula.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1.0, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Empty line below a formula",
    ),
    FormattingRule(
        id="common.bibliography.entry",
        source_doc=_COMMON_DOC,
        source_section="List of Used Sources",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "justify",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Bibliography entry: justified, paragraph indent, 1.5 line spacing",
    ),
    FormattingRule(
        id="common.figure.image",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "line_spacing": 1.5,
            "max_width_cm": 15,
            "dpi": (96, 96),
            "format": "PNG",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Image placement: centered, max width 15cm",
    ),
    FormattingRule(
        id="common.table.caption",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.5,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table caption: left-aligned, Times New Roman 14pt",
    ),
    FormattingRule(
        id="common.table.spacing_before",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 0.5, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Empty line above a table",
    ),
    FormattingRule(
        id="common.table.spacing_after",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"line_spacing": 1, "space_before_pt": 0, "space_after_pt": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Empty line below a table",
    ),
    FormattingRule(
        id="common.table.cell_padding",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"padding_pt": 6},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table cell vertical padding: 6pt before/after",
    ),
    FormattingRule(
        id="common.table.font.size",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"min_size_pt": 10, "max_size_pt": 12},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table text font size must be 10-12pt",
    ),
    FormattingRule(
        id="common.table.body",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={
            "font_size_pt": 12,
            "header_font_size_pt": 12,
            "header_bold": True,
            "line_spacing": 1.0,
            "header_repeat_on_pages": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description=("Table body: 12pt font, single spacing, bold header repeated on continuation pages"),
    ),
    FormattingRule(
        id="common.page.margins.landscape",
        source_doc=_COMMON_DOC,
        source_section="Page and Paper Setup",
        severity=RuleSeverity.REQUIRED,
        parameters={"top_mm": 30, "bottom_mm": 10, "left_mm": 20, "right_mm": 20},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="A4 landscape margins: top 30mm, bottom 10mm, left 20mm, right 20mm",
    ),
    FormattingRule(
        id="common.heading.h4",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "left",
            "bold": False,
            "line_spacing": 1.0,
            "indent_cm": 1.25,
            "space_before_pt": 0,
            "space_after_pt": 0,
        },
        description="H4 subpoint heading: mirrors H3 with paragraph indent 1.25 cm",
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
    ),
    FormattingRule(
        id="common.heading.no_hyphenation",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"allow_word_break": False},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Headings must not use word hyphenation",
    ),
    FormattingRule(
        id="common.heading.two_sentence_separator",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"separator": ".", "enforce": True},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Heading with two sentences must separate them with a period",
    ),
    FormattingRule(
        id="common.heading.point_requires_subpoints",
        source_doc=_COMMON_DOC,
        source_section="Headings",
        severity=RuleSeverity.REQUIRED,
        parameters={"min_subpoints": 2},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Point headings are used when a subsection has two or more points with subpoints",
    ),
    FormattingRule(
        id="common.list.lettered",
        source_doc=_COMMON_DOC,
        source_section="Division of Text",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "excluded_letters": "ёзйочьыъ",
            "format": "а)",
            "indent_cm": 1.25,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Lettered list uses lowercase Russian letters with closing parenthesis",
    ),
    FormattingRule(
        id="common.list.nested_numeric",
        source_doc=_COMMON_DOC,
        source_section="Division of Text",
        severity=RuleSeverity.REQUIRED,
        parameters={"format": "N)", "extra_indent_chars": 2},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Nested numeric list uses Arabic numerals with closing parenthesis, indented two characters",
    ),
    FormattingRule(
        id="common.list.marker_alphabetical",
        source_doc=_COMMON_DOC,
        source_section="Division of Text",
        severity=RuleSeverity.REQUIRED,
        parameters={"enforce_order": True, "sequence": "а)б)в)..."},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Lettered list markers must follow alphabetical order а), б), в), …",
    ),
    FormattingRule(
        id="common.formula.body_indent",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"indent_cm": 1.25},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Formula paragraph uses standard paragraph first-line indent 1.25 cm",
    ),
    FormattingRule(
        id="common.formula.section_numbering",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"pattern": "{section}.{n}", "default_enabled": False},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Section-based formula numbering pattern, e.g. (1.1)",
    ),
    FormattingRule(
        id="common.formula.appendix_numbering",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "{letter}.{n}"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Appendix formulas use separate numbering with appendix letter, e.g. (А.1)",
    ),
    FormattingRule(
        id="common.formula.line_continuation",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "break_on_operation_sign": True,
            "repeat_sign_on_next_line": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Long formulas break at operation signs with the sign repeated on the next line",
    ),
    FormattingRule(
        id="common.formula.explanation_marker",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"marker": "где", "trailing_colon": False, "indent_cm": 0},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="First explanation line must start with 'где', without a colon and without paragraph indent",
    ),
    FormattingRule(
        id="common.formula.repeated_symbol",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"reference_phrase": "то же, что и в формуле (N)"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Repeated symbols are not redefined; the standard phrase points to the prior formula",
    ),
    FormattingRule(
        id="common.formula.consecutive_comma",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"separator": ","},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Consecutive formulas with no text between them are separated by commas",
    ),
    FormattingRule(
        id="common.formula.cross_reference",
        source_doc=_COMMON_DOC,
        source_section="Formulas",
        severity=RuleSeverity.REQUIRED,
        parameters={"patterns": ("(N)", "(N.M)")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="References to formulas use parenthesised numbers such as (2) or (1.1)",
    ),
    FormattingRule(
        id="common.table.borders",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "left": True,
            "right": True,
            "bottom": True,
            "top": False,
            "header_double": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Tables are bounded left/right/bottom; the head is separated by a double line",
    ),
    FormattingRule(
        id="common.table.forbid_serial_column",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"forbidden_headers": ("Номер по порядку", "№ п/п")},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Tables must not include a separate 'Номер по порядку' / '№ п/п' column",
    ),
    FormattingRule(
        id="common.table.section_numbering",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"pattern": "Таблица {section}.{n}", "default_enabled": False},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Section-based table numbering, e.g. 'Таблица 7.1'",
    ),
    FormattingRule(
        id="common.table.appendix_numbering",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "Таблица {letter}.{n}"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix tables use the appendix letter, e.g. 'Таблица А.1'",
    ),
    FormattingRule(
        id="common.table.subheader",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "continuation_lowercase": True,
            "independent_uppercase": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Sub-headers are lowercase when continuing a sentence with the header, uppercase otherwise",
    ),
    FormattingRule(
        id="common.table.no_diagonal_split",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"forbid_diagonal_lines": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Headings and side headings must not be separated by diagonal lines",
    ),
    FormattingRule(
        id="common.table.no_period_in_header",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"allow_trailing_period": False},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table headers and sub-headers must not end with a period",
    ),
    FormattingRule(
        id="common.table.unit_label",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "position": "above_right",
            "font_size_pt": 12,
            "single_label": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="If all indicators share one unit, print it once above the table on the right at 12pt",
    ),
    FormattingRule(
        id="common.table.column_unit_suffix",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"suffix_pattern": ", {unit}", "examples": (", Гц",)},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Column-specific units are placed after the indicator name in the heading, separated by a comma",
    ),
    FormattingRule(
        id="common.table.numbering_row_replacement",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"replaces_header_on_continuation": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Continuation pages may replace the head with a numbering row for columns and side heading",
    ),
    FormattingRule(
        id="common.table.continuation_label",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "continuation": "Продолжение таблицы {N}",
            "final": "Окончание таблицы {N}",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Continuation and final parts of split tables use 'Продолжение таблицы N' / 'Окончание таблицы N'",
    ),
    FormattingRule(
        id="common.table.footnote",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "markers": ("*", "1)"),
            "placement": "above_closing_line",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Table footnotes use superscript '*' or '1)' markers and sit above the closing line",
    ),
    FormattingRule(
        id="common.table.italic_letters",
        source_doc=_COMMON_DOC,
        source_section="Tables",
        severity=RuleSeverity.REQUIRED,
        parameters={"italic": True, "standard": "GOST 2.321"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Letter designations from GOST 2.321 are rendered in italics",
    ),
    FormattingRule(
        id="common.figure.section_numbering",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"pattern": "Рисунок {section}.{n}", "default_enabled": False},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Section-based figure numbering, e.g. 'Рисунок 7.1'",
    ),
    FormattingRule(
        id="common.figure.appendix_numbering",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "Рисунок {letter}.{n}"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Appendix figures use the appendix letter, e.g. 'Рисунок А.1'",
    ),
    FormattingRule(
        id="common.figure.placement_after_reference",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"placement": "after_first_reference_or_next_page"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Figures appear directly after the first reference or on the next page",
    ),
    FormattingRule(
        id="common.figure.explanatory_data",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={"position": "above_caption", "font_size_pt": 12},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Explanatory data sits above the figure caption at 12pt",
    ),
    FormattingRule(
        id="common.figure.multi_sheet_label",
        source_doc=_COMMON_DOC,
        source_section="Illustrations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "first_label": "лист 1",
            "subsequent_label": "Рисунок {N}, лист {sheet}",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Multi-sheet figures label sheets 'лист 1', 'Рисунок N, лист 2', and so on",
    ),
    FormattingRule(
        id="common.bibliography.gost_record",
        source_doc=_COMMON_DOC,
        source_section="List of Used Sources",
        severity=RuleSeverity.REQUIRED,
        parameters={"standards": ("ГОСТ Р 7.0.100", "ГОСТ 7.80")},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Bibliographic records follow ГОСТ Р 7.0.100 and ГОСТ 7.80",
    ),
    FormattingRule(
        id="common.bibliography.gost_abbreviations",
        source_doc=_COMMON_DOC,
        source_section="List of Used Sources",
        severity=RuleSeverity.REQUIRED,
        parameters={"standards": ("ГОСТ 7.11", "ГОСТ Р 7.0.12")},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Word reductions in bibliographic records follow ГОСТ 7.11 / ГОСТ Р 7.0.12",
    ),
    FormattingRule(
        id="common.bibliography.grouping_method",
        source_doc=_COMMON_DOC,
        source_section="List of Used Sources",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "allowed_methods": ("alphabetical", "systematic", "chronological"),
            "mixing_forbidden": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Use a single grouping method: alphabetical, systematic, or chronological",
    ),
    FormattingRule(
        id="common.bibliography.russian_first",
        source_doc=_COMMON_DOC,
        source_section="List of Used Sources",
        severity=RuleSeverity.REQUIRED,
        parameters={"russian_section_first": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Russian-language entries appear before non-Russian entries",
    ),
    FormattingRule(
        id="common.reference.in_text_simple",
        source_doc=_COMMON_DOC,
        source_section="Bibliographic References in Text",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "[N]"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Simple in-text source reference uses square brackets with the source number",
    ),
    FormattingRule(
        id="common.reference.in_text_pages",
        source_doc=_COMMON_DOC,
        source_section="Bibliographic References in Text",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "[N, с. M]", "allow_page_ranges": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="In-text reference with pages, e.g. [20, с. 29] or page ranges",
    ),
    FormattingRule(
        id="common.reference.in_text_volume",
        source_doc=_COMMON_DOC,
        source_section="Bibliographic References in Text",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "[N, т. T, с. M]"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="In-text reference for multivolume sources, e.g. [18, т. 1, с. 75]",
    ),
    FormattingRule(
        id="common.reference.in_text_group",
        source_doc=_COMMON_DOC,
        source_section="Bibliographic References in Text",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "[N; N, с. M-K; N]", "separator": ";"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Grouped references separate sources with semicolons, e.g. [59; 67, с. 40-46; 82]",
    ),
    FormattingRule(
        id="common.reference.footnote",
        source_doc=_COMMON_DOC,
        source_section="Bibliographic References in Text",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "marker": "superscript_numeric",
            "separator_line": True,
            "font_size_reduction": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Footnote references use a thin separator line and a reduced font size",
    ),
    FormattingRule(
        id="common.reference.cross_check",
        source_doc=_COMMON_DOC,
        source_section="Bibliographic References in Text",
        severity=RuleSeverity.REQUIRED,
        parameters={"enforce_bibliography_match": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Each [N] reference must resolve to a bibliography entry",
    ),
    FormattingRule(
        id="common.reference.figure_table_formula",
        source_doc=_COMMON_DOC,
        source_section="Bibliographic References in Text",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "patterns": (
                "(рисунок N)",
                "(таблица N)",
                "(N)",
                "(приложение А)",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="In-text references to figures/tables/formulas/appendices follow standard phrasing",
    ),
    FormattingRule(
        id="common.appendix.heading",
        source_doc=_COMMON_DOC,
        source_section="Appendices",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alignment": "center",
            "bold": True,
            "line_spacing": 1.0,
            "indent_cm": 0,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "uppercase": True,
            "page_break_before": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Appendix heading: page break, centered, bold, uppercase",
    ),
    FormattingRule(
        id="common.appendix.auto_letter",
        source_doc=_COMMON_DOC,
        source_section="Appendices",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "alphabet": "А",
            "skip_letters": ("Ё", "З", "Й", "О", "Ч", "Ь", "Ы", "Ъ"),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendices are auto-assigned Russian letters skipping Ё, З, Й, О, Ч, Ь, Ы, Ъ",
    ),
    FormattingRule(
        id="common.appendix.continuation_label",
        source_doc=_COMMON_DOC,
        source_section="Appendices",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "continuation": "Продолжение приложения {letter}",
            "final": "Окончание приложения {letter}",
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Multi-page appendices use 'Продолжение приложения А' / 'Окончание приложения А'",
    ),
    FormattingRule(
        id="common.appendix.section_numbering",
        source_doc=_COMMON_DOC,
        source_section="Appendices",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "patterns": ("{letter}.N", "{letter}.N.M", "{letter}.N.M.K", "{letter}.N.M.K.L"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix internal numbering prefixes section/subsection numbers with the appendix letter",
    ),
    FormattingRule(
        id="common.appendix.in_text_reference",
        source_doc=_COMMON_DOC,
        source_section="Appendices",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "phrases": (
                "в соответствии с приложением {letter}",
                "приведен в приложении {letter}",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="References to appendices use the standard phrasing with appendix letter",
    ),
    FormattingRule(
        id="common.appendix.sheet_format",
        source_doc=_COMMON_DOC,
        source_section="Appendices",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"allowed_formats": ("А4", "А3", "А3×4", "А4×4", "А2", "А1")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix sheets may use formats А4, А3, А3×4, А4×4, А2, А1 per GOST 2.301",
    ),
    FormattingRule(
        id="common.abbreviations.two_column_layout",
        source_doc=_COMMON_DOC,
        source_section="List of Abbreviations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "left_column": "abbreviation_alphabetical",
            "right_column": "expansion",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Abbreviations list is a two-column layout: abbreviation, then full expansion",
    ),
    FormattingRule(
        id="common.referat.template",
        source_doc=_COMMON_DOC,
        source_section="Core Text Document Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "counts": ("страницы", "рисунки", "таблицы", "формулы", "приложения", "источники"),
            "max_keywords": 15,
            "max_pages": 1,
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Referat lists volume counts, up to 15 keywords, and fits within one page",
    ),
    FormattingRule(
        id="common.referat.keywords_uppercase",
        source_doc=_COMMON_DOC,
        source_section="Core Text Document Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "case": "uppercase",
            "separator": ", ",
            "grammatical_case": "nominative",
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Referat keywords are uppercase, comma-separated, in nominative case",
    ),
    FormattingRule(
        id="common.style.abbreviation_introduction",
        source_doc=_COMMON_DOC,
        source_section="List of Abbreviations",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "pattern": "{full term} ({abbreviation})",
            "example": "информационно-аналитический комплекс (ИАК)",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Custom abbreviations are introduced at first mention as 'full term (ABBR)'",
    ),
    FormattingRule(
        id="common.style.no_abbreviations_in_headings",
        source_doc=_COMMON_DOC,
        source_section="List of Abbreviations",
        severity=RuleSeverity.REQUIRED,
        parameters={"forbid_in": ("section_heading", "subsection_heading", "point_heading")},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Headings of sections/subsections/points must not contain abbreviations",
    ),
    FormattingRule(
        id="common.style.unit_consistency",
        source_doc=_COMMON_DOC,
        source_section="Text Style and Terminology",
        severity=RuleSeverity.REQUIRED,
        parameters={"standard": "GOST 8.417", "one_unit_per_quantity": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="The same parameter must use the same unit throughout the document (ГОСТ 8.417)",
    ),
)


LAB_PRACTICAL_PROJECT_REPORT_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="lab_practical_project_reports.metadata.required",
        source_doc=_LAB_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("document_type", "title", "student", "group", "teacher"),
            "optional_metadata": ("record_book", "institute", "department", "city", "year"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Lab/practical/project report metadata required by the title page form",
    ),
    FormattingRule(
        id="lab_practical_project_reports.title_page.form_m",
        source_doc=_LAB_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_m",
            "default_document_type": "ОТЧЕТ ПО ЛАБОРАТОРНОЙ РАБОТЕ",
            "required_metadata": ("title", "student", "group", "teacher"),
            "optional_metadata": ("document_type", "record_book", "institute", "department", "city", "year"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix M title page for lab, practical, and project-completion reports",
    ),
    FormattingRule(
        id="lab_practical_project_reports.structure.required_sections",
        source_doc=_LAB_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


PRACTICE_REPORT_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="practice_reports.metadata.required",
        source_doc=_PRACTICE_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "practice_place",
                "university_supervisor",
                "enterprise_supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Practice report metadata required by the title page form",
    ),
    FormattingRule(
        id="practice_reports.title_page.form_k",
        source_doc=_PRACTICE_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_k",
            "default_document_type": "ОТЧЕТ О ПРАКТИКЕ",
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "practice_place",
                "university_supervisor",
                "enterprise_supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix K title page for practice reports",
    ),
    FormattingRule(
        id="practice_reports.title_page.form_k.headings",
        source_doc=_PRACTICE_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "variants": (
                "ОТЧЕТ ОБ УЧЕБНОЙ ПРАКТИКЕ",
                "ОТЧЕТ О ПРОИЗВОДСТВЕННОЙ ПРАКТИКЕ",
                "ОТЧЕТ О ПРЕДДИПЛОМНОЙ ПРАКТИКЕ",
                "ОТЧЕТ О ТЕХНОЛОГИЧЕСКОЙ ПРАКТИКЕ",
            ),
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Form К supports four practice-report heading variants: учебная, производственная, преддипломная, технологическая",
    ),
    FormattingRule(
        id="practice_reports.structure.required_sections",
        source_doc=_PRACTICE_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


RESEARCH_REPORT_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="research_reports.metadata.required",
        source_doc=_RESEARCH_DOC,
        source_section="Title Page for Master's Research-Work Report",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "master_program",
                "program_head",
                "approval_date",
                "supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Research report metadata required by the title page form",
    ),
    FormattingRule(
        id="research_reports.title_page.form_l",
        source_doc=_RESEARCH_DOC,
        source_section="Title Page for Master's Research-Work Report",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_l",
            "default_document_type": "ОТЧЕТ О НАУЧНО-ИССЛЕДОВАТЕЛЬСКОЙ РАБОТЕ",
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "master_program",
                "program_head",
                "approval_date",
                "supervisor",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix L title page for master's research-work reports",
    ),
    FormattingRule(
        id="research_reports.structure.required_sections",
        source_doc=_RESEARCH_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


SMALL_WRITTEN_WORK_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="small_written_works.metadata.required",
        source_doc=_SMALL_WRITTEN_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "discipline",
                "teacher",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Small written work metadata required by the title page form",
    ),
    FormattingRule(
        id="small_written_works.title_page.form_n",
        source_doc=_SMALL_WRITTEN_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_n",
            "default_document_type": "РЕФЕРАТ",
            "required_metadata": ("title", "student", "group"),
            "optional_metadata": (
                "document_type",
                "discipline",
                "teacher",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix N title page for referats, calculation works, control works, and essays",
    ),
    FormattingRule(
        id="small_written_works.structure.required_sections",
        source_doc=_SMALL_WRITTEN_DOC,
        source_section="Structure",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory",
    ),
)


COURSEWORK_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="coursework.metadata.required",
        source_doc=_COURSEWORK_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "group", "supervisor"),
            "optional_metadata": (
                "document_type",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Coursework metadata required by the title page form",
    ),
    FormattingRule(
        id="coursework.title_page.form_i",
        source_doc=_COURSEWORK_DOC,
        source_section="Title Page",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_i",
            "default_document_type": "КУРСОВАЯ РАБОТА",
            "required_metadata": ("title", "student", "group", "supervisor"),
            "optional_metadata": (
                "document_type",
                "record_book",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix I title page for course projects and course works",
    ),
    FormattingRule(
        id="coursework.structure.required_sections",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Work Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_blocks": ("title_page", "main_part")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Title page and main part are mandatory for course works",
    ),
    FormattingRule(
        id="coursework.toc.form_t",
        source_doc=_COURSEWORK_DOC,
        source_section="Contents Example Pattern",
        severity=RuleSeverity.REQUIRED,
        parameters={"form": "appendix_t", "enabled_when_metadata": {"course_work": True}},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Course works use Appendix T as the contents layout reference",
    ),
    FormattingRule(
        id="coursework.frame.course_project_explanatory_note",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Project Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"requires_frame": True, "title_block_forms": ("form_1", "form_2", "form_3", "form_4")},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Course project explanatory notes use framed sheets and title blocks",
    ),
    FormattingRule(
        id="coursework.title_block.field_2_designation",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Project Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"title_block_field": 2, "source": "project_designations"},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Field 2 of the course-project title block holds the letter-numeric designation",
    ),
    FormattingRule(
        id="coursework.title_block.field_7_page_number",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Project Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"title_block_field": 7},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Page number on framed course-project sheets goes into field 7 of the title block",
    ),
    FormattingRule(
        id="coursework.metadata.required_designation",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Project Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_metadata": ("project_designation",)},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Course projects must supply a letter-numeric designation in metadata",
    ),
    FormattingRule(
        id="coursework.appendix.sheet_format",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Project Specifics",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"allowed_formats": ("А4", "А3", "А3×4", "А4×4", "А2", "А1")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Course-project appendix sheets may use formats А4, А3, А3×4, А4×4, А2, А1",
    ),
    FormattingRule(
        id="coursework.formula.section_numbering",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Work Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "{section}.{n}", "default_enabled": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Coursework uses section-based formula numbering by default",
    ),
    FormattingRule(
        id="coursework.table.section_numbering",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Work Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "Таблица {section}.{n}", "default_enabled": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Coursework uses section-based table numbering by default",
    ),
    FormattingRule(
        id="coursework.figure.section_numbering",
        source_doc=_COURSEWORK_DOC,
        source_section="Course Work Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "Рисунок {section}.{n}", "default_enabled": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Coursework uses section-based figure numbering by default",
    ),
)


GRADUATION_QUALIFICATION_WORK_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="graduation_qualification_work.metadata.required",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("title", "student", "supervisor"),
            "optional_metadata": (
                "vkr_type",
                "direction",
                "program",
                "reviewer",
                "department_head",
                "institute",
                "department",
                "city",
                "year",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR metadata required by the selected title page form",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_b",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_b",
            "document_type": "МАГИСТЕРСКАЯ ДИССЕРТАЦИЯ",
            "default_document_type": "МАГИСТЕРСКАЯ ДИССЕРТАЦИЯ",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix B title page for master dissertations",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_v",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_v",
            "document_type": "ДИПЛОМНЫЙ ПРОЕКТ",
            "default_document_type": "ДИПЛОМНЫЙ ПРОЕКТ",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix V title page for diploma projects",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_g",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_g",
            "document_type": "ДИПЛОМНАЯ РАБОТА",
            "default_document_type": "ДИПЛОМНАЯ РАБОТА",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix G title page for diploma works",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_d",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_d",
            "document_type": "БАКАЛАВРСКАЯ РАБОТА",
            "default_document_type": "БАКАЛАВРСКАЯ РАБОТА",
            "required_metadata": ("title", "student", "supervisor"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix D title page for bachelor works",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_e",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_e",
            "purpose": "vkr_continuation_page",
            "default_document_type": "",
            "required_metadata": ("title", "consultants", "norm_controller"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix Е additional VKR title-page page with consultants and norm controller",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_zh",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Title Pages",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_zh",
            "purpose": "single_page_combined",
            "default_document_type": "ВЫПУСКНАЯ КВАЛИФИКАЦИОННАЯ РАБОТА",
            "required_metadata": ("title", "student", "supervisor", "reviewer", "consultants", "norm_controller"),
            "max_consultants": 2,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Appendix Ж single-page VKR title page combining reviewer, consultants, and norm controller",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_b.required_metadata",
        source_doc=_GRADUATION_DOC,
        source_section="Master Dissertation Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": (
                "direction_code",
                "direction_name",
                "master_program_code",
                "master_program_name",
                "reviewer",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Form Б extends required metadata with direction, master program, and reviewer fields",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_v.required_metadata",
        source_doc=_GRADUATION_DOC,
        source_section="Diploma Project Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "required_metadata": ("specialty_code",),
            "subtitle": "Пояснительная записка",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Form В adds specialty code and 'Пояснительная записка' subtitle",
    ),
    FormattingRule(
        id="graduation_qualification_work.title_page.form_g.required_metadata",
        source_doc=_GRADUATION_DOC,
        source_section="Diploma Work Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"required_metadata": ("reviewer",)},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Form Г adds reviewer to required metadata",
    ),
    FormattingRule(
        id="graduation_qualification_work.referat.required",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Abstract (`Реферат ВКР`)",
        severity=RuleSeverity.REQUIRED,
        parameters={"form": "appendix_p", "generator_enabled": True},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR must include the Form П referat generated from document statistics",
    ),
    FormattingRule(
        id="graduation_qualification_work.assignment.form_a",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Assignment",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "form": "appendix_a",
            "placement": "after_title_page",
            "counted_in_page_total": False,
        },
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR includes the assignment generated from Form А, placed after the title page",
    ),
    FormattingRule(
        id="graduation_qualification_work.appendix.sheet_format",
        source_doc=_GRADUATION_DOC,
        source_section="Graphic and Demonstration Materials for Defense",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"allowed_formats": ("А4", "А3", "А3×4", "А4×4", "А2", "А1")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR appendix sheets may use formats А4, А3, А3×4, А4×4, А2, А1",
    ),
    FormattingRule(
        id="graduation_qualification_work.structure.assignment_after_title",
        source_doc=_GRADUATION_DOC,
        source_section="VKR Assignment",
        severity=RuleSeverity.REQUIRED,
        parameters={"assignment_after_title_page": True, "counted_in_page_total": False},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR assignment is inserted after the title page and excluded from page count",
    ),
    FormattingRule(
        id="graduation_qualification_work.formula.section_numbering",
        source_doc=_GRADUATION_DOC,
        source_section="Master Dissertation Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "{section}.{n}", "default_enabled": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR uses section-based formula numbering by default",
    ),
    FormattingRule(
        id="graduation_qualification_work.table.section_numbering",
        source_doc=_GRADUATION_DOC,
        source_section="Master Dissertation Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "Таблица {section}.{n}", "default_enabled": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR uses section-based table numbering by default",
    ),
    FormattingRule(
        id="graduation_qualification_work.figure.section_numbering",
        source_doc=_GRADUATION_DOC,
        source_section="Master Dissertation Specifics",
        severity=RuleSeverity.REQUIRED,
        parameters={"pattern": "Рисунок {section}.{n}", "default_enabled": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="VKR uses section-based figure numbering by default",
    ),
)


GRAPHIC_AND_DEMONSTRATION_MATERIAL_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="graphic_and_demonstration_materials.sheet.frame",
        source_doc=_GRAPHIC_DOC,
        source_section="Drawings and Schemes",
        severity=RuleSeverity.REQUIRED,
        parameters={"requires_frame": True, "title_block_forms": ("form_5", "form_6")},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Drawings and schemes require a frame and title block",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.poster.fill_density",
        source_doc=_GRAPHIC_DOC,
        source_section="Posters",
        severity=RuleSeverity.REQUIRED,
        parameters={"min_fill_percent": 70, "format": "A1"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Posters are A1 sheets filled to at least 70 percent",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.slide.required_first_slide_fields",
        source_doc=_GRAPHIC_DOC,
        source_section="Slides",
        severity=RuleSeverity.REQUIRED,
        parameters={"fields": ("university", "institute", "title", "student", "supervisor", "city", "year")},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="First slide must include institution, topic, author, supervisor, city, and year",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.drawing.frame_form_5_or_6",
        source_doc=_GRAPHIC_DOC,
        source_section="Drawings and Schemes",
        severity=RuleSeverity.REQUIRED,
        parameters={"allowed_forms": ("form_5", "form_6"), "placement": "front_lower_right"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Drawing sheets use title block form 5 or 6 placed front-side lower-right",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.drawing.scale_set",
        source_doc=_GRAPHIC_DOC,
        source_section="Drawings and Schemes",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "standard": "GOST 2.302",
            "scales": (
                "1:1",
                "1:2",
                "1:2.5",
                "1:4",
                "1:5",
                "1:10",
                "1:15",
                "1:20",
                "1:25",
                "1:40",
                "1:50",
                "1:75",
                "1:100",
                "1:200",
                "1:400",
                "1:500",
                "1:800",
                "2:1",
                "2.5:1",
                "4:1",
                "5:1",
                "10:1",
                "20:1",
                "40:1",
                "50:1",
                "100:1",
            ),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Drawing scales must come from the ГОСТ 2.302 list",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.drawing.font_set",
        source_doc=_GRAPHIC_DOC,
        source_section="Drawings and Schemes",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "standard": "GOST 2.304",
            "font_types": ("type_A", "type_B"),
            "with_or_without_slant": True,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Drawing fonts must follow ГОСТ 2.304 (types A and B, with or without slant)",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.poster.title_block_on_reverse",
        source_doc=_GRAPHIC_DOC,
        source_section="Posters",
        severity=RuleSeverity.REQUIRED,
        parameters={"title_block_side": "reverse"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Poster title block is placed on the reverse side of the sheet",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.slide.fill_density",
        source_doc=_GRAPHIC_DOC,
        source_section="Slides",
        severity=RuleSeverity.REQUIRED,
        parameters={"min_fill_percent": 70},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Slide fill density must be at least 70 percent",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.slide.header_continuity",
        source_doc=_GRAPHIC_DOC,
        source_section="Slides",
        severity=RuleSeverity.REQUIRED,
        parameters={"reuse_heading_on_continuation": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="When content spills to the next slide the heading is repeated",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.slide.a4_print_out",
        source_doc=_GRAPHIC_DOC,
        source_section="Slides",
        severity=RuleSeverity.REQUIRED,
        parameters={"print_format": "A4", "purpose": "handout"},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Slides are printed on A4 sheets for use as handouts during defense",
    ),
    FormattingRule(
        id="graphic_and_demonstration_materials.appendix.sheet_format",
        source_doc=_GRAPHIC_DOC,
        source_section="Drawings and Schemes",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"allowed_formats": ("А4", "А3", "А3×4", "А4×4", "А2", "А1")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Graphic appendix sheets may use formats А4, А3, А3×4, А4×4, А2, А1",
    ),
)


PROJECT_DESIGNATION_RULES: tuple[FormattingRule, ...] = (
    FormattingRule(
        id="project_designations.explanatory_note.frame",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Explanatory Note Sheets",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "left_sheet_edge_to_frame_mm": 20,
            "top_right_bottom_edge_to_frame_mm": 5,
            "text_to_frame_horizontal_mm": 5,
            "text_to_frame_vertical_mm": 15,
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Diploma and course project explanatory notes use framed A4 sheets",
    ),
    FormattingRule(
        id="project_designations.title_block.forms",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Main Title-Block Forms",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "text_first_sheet_forms": ("form_1", "form_2"),
            "text_following_sheet_forms": ("form_3", "form_4"),
            "graphic_sheet_forms": ("form_5", "form_6"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Title-block forms used for explanatory notes and graphic sheets",
    ),
    FormattingRule(
        id="project_designations.title_block.letter_numeric_designation",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Letter-Numeric Designation",
        severity=RuleSeverity.REQUIRED,
        parameters={"title_block_field": 2, "may_include_year": True},
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Diploma/course project materials receive a letter-numeric designation in title-block field 2",
    ),
    FormattingRule(
        id="project_designations.code.dictionary",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Document Codes from `Приложение Х`",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "document_codes": (
                "ПЗ",
                "РР",
                "ПМ",
                "И",
                "Д",
                "ВС",
                "ВП",
                "ТБ",
                "ТУ",
                "СБ",
                "ВО",
                "ТЧ",
                "ГЧ",
                "МЭ",
                "МЧ",
                "УЧ",
                "МК",
                "КТП",
                "ОК",
                "ВОБ",
                "ВМ",
                "С",
                "ЛС",
                "ТХ",
                "ГП",
                "ГТ",
                "АР",
                "АС",
                "АИ",
                "КЖ",
                "КМ",
                "КМД",
                "КД",
                "ВК",
                "ОВ",
                "ТМ",
                "ГСВ",
                "ГР",
                "НВ",
                "НК",
                "ТС",
                "АД",
                "ТР",
            ),
            "scheme_type_codes": ("Э", "Г", "П", "К", "В", "Л", "Р", "Е", "С"),
            "scheme_subtype_numbers": ("1", "2", "3", "4", "5", "6", "7", "0"),
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Full enum of document codes from Приложение Х plus scheme type/subtype codes",
    ),
    FormattingRule(
        id="project_designations.code.format",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Letter-Numeric Designation",
        severity=RuleSeverity.REQUIRED,
        parameters={
            "pattern": r"^[А-Я]{2,3}[-–—] ?\d{2}\.\d{2}\.\d{2}( ?\w+){0,3}( [А-Я]{1,3})?$",
        },
        renderer_status=RuleStatus.IMPLEMENTED,
        validator_status=RuleStatus.IMPLEMENTED,
        description="Project designation regex covering work code, specialty, optional fields, and document code",
    ),
    FormattingRule(
        id="project_designations.code.year_optional",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Letter-Numeric Designation",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"year_suffix_pattern": r"–\d{4}"},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Optional `–YYYY` suffix may follow the specialty/specialization number",
    ),
    FormattingRule(
        id="project_designations.appendix.sheet_format",
        source_doc=_PROJECT_DESIGNATION_DOC,
        source_section="Explanatory Note Sheets",
        severity=RuleSeverity.RECOMMENDED,
        parameters={"allowed_formats": ("А4", "А3", "А3×4", "А4×4", "А2", "А1")},
        renderer_status=RuleStatus.NOT_SUPPORTED,
        validator_status=RuleStatus.NOT_SUPPORTED,
        description="Project-designation appendix sheets may use formats А4, А3, А3×4, А4×4, А2, А1",
    ),
)


ALL_RULES: tuple[FormattingRule, ...] = (
    *COMMON_RULES,
    *LAB_PRACTICAL_PROJECT_REPORT_RULES,
    *PRACTICE_REPORT_RULES,
    *RESEARCH_REPORT_RULES,
    *SMALL_WRITTEN_WORK_RULES,
    *COURSEWORK_RULES,
    *GRADUATION_QUALIFICATION_WORK_RULES,
    *GRAPHIC_AND_DEMONSTRATION_MATERIAL_RULES,
    *PROJECT_DESIGNATION_RULES,
)

RULES_BY_ID: dict[str, FormattingRule] = {rule.id: rule for rule in ALL_RULES}
