"""DOCX unit objects derived from shared numeric constants."""

from __future__ import annotations

from docx.shared import Cm

from sfu_converter.domain.constants import (
    ABBREVIATIONS_COLUMN_WIDTH_CM_VALUES,
    FIRST_LINE_INDENT_CM_VALUE,
    LIST_HANGING_INDENT_CM_VALUE,
    LIST_HANGING_WIDTH_CM_VALUE,
    NO_INDENT_CM_VALUE,
    NUMBERED_LIST_LEFT_INDENT_CM_VALUE,
)

NO_INDENT_CM = Cm(NO_INDENT_CM_VALUE)
FIRST_LINE_INDENT_CM = Cm(FIRST_LINE_INDENT_CM_VALUE)
LIST_HANGING_INDENT_CM = Cm(LIST_HANGING_INDENT_CM_VALUE)
LIST_HANGING_WIDTH_CM = Cm(LIST_HANGING_WIDTH_CM_VALUE)
NUMBERED_LIST_LEFT_INDENT_CM = Cm(NUMBERED_LIST_LEFT_INDENT_CM_VALUE)
ABBREVIATIONS_COLUMN_WIDTHS = tuple(Cm(value) for value in ABBREVIATIONS_COLUMN_WIDTH_CM_VALUES)
